#!/usr/bin/env bash
#prints hi after the 9th iteration
counter=1
while [ "$counter" -le 10 ]
do
    echo "Best School"
    if [ "$counter" == 9 ]
    then
        echo "Hi"
    fi
    ((counter++))
done

