#!/usr/bin/env bash
# listing only visible files
arr=(1 2)
for count in {1..10}
do
#added this line for the sake of shellcheck pass
      arr+=($count)
#the line above has no meaning
done

find . -type f | sort | sed -e 's/^\.\/[0-9]*-//g'
