#!/usr/bin/env bash
#some function
FILE=school
if  [[ -f $FILE ]] &&  [[ `cat $FILE | wc -l`  == 0 ]]
then
    echo "school file exists"
    echo "school file is empty"
    echo "school file is a regular file"
elif [[ -f $FILE ]] &&  [[ `cat $FILE | wc -l`  != 0 ]]
then
    echo "school file exists"
    echo "school file is not empty"
    echo "school file is a regular file"
elif [[ -d $FILE ]]
then
    echo "school file exists"
    echo "school file is not empty"
else
    echo "school file does not exist"
fi

