#!/usr/bin/env bash
#some function
FILE=school
if  [[ -f "$FILE" ]] &&  [[ "$(cat $FILE | wc -l)"  == 0 ]]
then
    echo "$FILE file exists"
    echo "$FILE file is empty"
    echo "$FILE is a regular file"
elif [[ -f "$FILE" ]] &&  [[ "$(cat $FILE | wc -l)"  != 0 ]]
then
    echo "$FILE file exists"
    echo "$FILE file is not empty"
    echo "$FILE is a regular file"
elif [[ -d "$FILE" ]]
then
    echo "$FILE file exists"
    echo "$FILE file is not empty"
else
    echo "$FILE file does not exist"
fi

